import {
  Activity,
  Airplay,
  Anchor,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  Bookmark,
  Camera,
  Check,
  Cloud,
  Code,
  Cpu,
  Database,
  Edit,
  File,
  Folder,
  Heart,
  Home,
  Key,
  Lightbulb,
  Lock,
  Mail,
  Map,
  Mic,
  Monitor,
  Mouse,
  Music,
  Phone,
  PieChart,
  Printer,
  Search,
  Send,
  Settings,
  Shield,
  ShoppingCart,
  Star,
  Sun,
  Tag,
  Trash,
  Unlock,
  User,
  Wifi,
  Icon
} from 'lucide-react'
import Link from 'next/link'
import { Card } from 'react-bootstrap'

export type LucideType = {
  icon: any
  name: string
}

export const lucideData: LucideType[] = [
  { icon: Activity, name: "activity" },
  { icon: Airplay, name: "airplay" },
  { icon: Anchor, name: "anchor" },
  { icon: Archive, name: "archive" },
  { icon: ArrowDown, name: "arrow-down" },
  { icon: ArrowLeft, name: "arrow-left" },
  { icon: ArrowRight, name: "arrow-right" },
  { icon: ArrowUp, name: "arrow-up" },
  { icon: Bell, name: "bell" },
  { icon: Bookmark, name: "bookmark" },
  { icon: Camera, name: "camera" },
  { icon: Check, name: "check" },
  { icon: Cloud, name: "cloud" },
  { icon: Code, name: "code" },
  { icon: Cpu, name: "cpu" },
  { icon: Database, name: "database" },
  { icon: Edit, name: "edit" },
  { icon: File, name: "file" },
  { icon: Folder, name: "folder" },
  { icon: Heart, name: "heart" },
  { icon: Home, name: "home" },
  { icon: Key, name: "key" },
  { icon: Lightbulb, name: "lightbulb" },
  { icon: Lock, name: "lock" },
  { icon: Mail, name: "mail" },
  { icon: Map, name: "map" },
  { icon: Mic, name: "mic" },
  { icon: Monitor, name: "monitor" },
  { icon: Mouse, name: "mouse" },
  { icon: Music, name: "music" },
  { icon: Phone, name: "phone" },
  { icon: PieChart, name: "pie-chart" },
  { icon: Printer, name: "printer" },
  { icon: Search, name: "search" },
  { icon: Send, name: "send" },
  { icon: Settings, name: "settings" },
  { icon: Shield, name: "shield" },
  { icon: ShoppingCart, name: "shopping-cart" },
  { icon: Star, name: "star" },
  { icon: Sun, name: "sun" },
  { icon: Tag, name: "tag" },
  { icon: Trash, name: "trash" },
  { icon: Unlock, name: "unlock" },
  { icon: User, name: "user" },
  { icon: Wifi, name: "wifi" }
]