export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/email/login',
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
    REGISTER: '/auth/email/register',
    FORGOT_PASSWORD: '/auth/forgot/password',
    RESET_PASSWORD: '/auth/reset/password',
    MFA_VERIFY: '/auth/mfa/verify',
  },
  STUDENTS: {
    LIST: '/students',
    BY_ID: (id: string) => `/students/${id}`,
    ENROLL: '/students',
    PROMOTE: (id: string) => `/students/${id}/promote`,
    GUARDIAN_LINK: (id: string) => `/students/${id}/guardians`,
    SIBLING_LINK: (id: string) => `/students/${id}/siblings`,
    GENERATE_ID: (id: string) => `/students/${id}/id-card`,
    TIMELINE: (id: string) => `/students/${id}/timeline`,
    DOCUMENTS: (id: string) => `/students/${id}/documents`,
    SEARCH: '/students/search',
  },
  TEACHERS: {
    LIST: '/teachers',
    BY_ID: (id: string) => `/teachers/${id}`,
    ENROLL: '/teachers',
    ATTENDANCE: '/teachers/attendance',
    LEAVE: '/teachers/leave',
    LEAVE_BY_ID: (id: string) => `/teachers/leave/${id}`,
    SUBSTITUTE: '/teachers/substitute',
    PAYROLL: '/teachers/payroll',
    WORKLOAD: (id: string) => `/teachers/${id}/workload`,
    DIRECTORY: '/teachers/directory',
  },
  ATTENDANCE: {
    MARK: '/attendance',
    BULK: '/attendance/bulk',
    SUBJECT: '/attendance/subject',
    REPORTS: '/attendance/reports',
    BY_STUDENT: (id: string) => `/attendance/student/${id}`,
    BY_CLASS: '/attendance/class',
    CALENDAR: '/attendance/calendar',
  },
  GRADES: {
    TERMS: '/grades/terms',
    ASSESSMENT_PLANS: '/grades/assessment-plans',
    MY_SUBJECT_PLANS: '/grades/assessment-plans/my-subjects',
    ASSESSMENTS: '/grades/assessments',
    ASSESSMENT_OVERRIDE: (id: string) => `/grades/assessments/${id}/override`,
    EXAMS: '/exams',
    EXAM_BY_ID: (id: string) => `/exams/${id}`,
    MARKS: '/grades/marks',
    MARKS_BULK: '/grades/marks/bulk',
    GRADING_BANDS: '/grades/grading-bands',
    RESULTS_SUBJECT: '/grades/results/subject',
    RESULTS_TERM: '/grades/results/term',
    RESULTS_CLASS: '/grades/results/class',
    PUBLISH_CLASS_RESULTS: '/grades/results/publish',
    REPORT_CARDS: '/report-cards',
    REPORT_CARD_BY_ID: (id: string) => `/report-cards/${id}`,
    PUBLISH: (examId: string) => `/exams/${examId}/publish`,
    ANALYTICS: '/grades/analytics',
    CORRECTION: (id: string) => `/marks/${id}/correction`,
  },
  FEES: {
    STRUCTURE: '/fees/structure',
    STRUCTURE_BY_ID: (id: number) => `/fees/structure/${id}`,
    GENERATE_INVOICES: '/fees/invoices/generate',
    INVOICES: '/fees/invoices',
    INVOICE_BY_ID: (id: string) => `/fees/invoices/${id}`,
    PAYMENTS: '/fees/payments',
    DISCOUNTS: '/fees/discounts',
    SEND_DUE_REMINDERS: '/fees/reminders/due-soon',
    SEND_OVERDUE_NOTICES: '/fees/reminders/overdue',
    WAIVER_REQUESTS: '/fees/waiver-requests',
    WAIVER_REQUEST_APPROVE: (id: string) => `/fees/waiver-requests/${id}/approve`,
    WAIVER_REQUEST_REJECT: (id: string) => `/fees/waiver-requests/${id}/reject`,
    REPORTS: '/fees/reports',
    DASHBOARD: '/fees/dashboard',
  },
  LIBRARY: {
    BOOKS: '/library/books',
    BOOK_BY_ID: (id: string) => `/library/books/${id}`,
    BOOKS_BY_BARCODE: (barcode: string) => `/library/books/barcode/${barcode}`,
    ISSUANCE: '/library/issuance',
    LOANS: '/library/loans',
    LOANS_RETURN: (id: string) => `/library/loans/${id}/return`,
    FINES: '/library/fines',
    FINES_PAY: (loanId: string) => `/library/fines/${loanId}/pay`,
    DIGITAL_BOOKS: '/library/digital-books',
    DIGITAL_BOOK_BY_ID: (id: string) => `/library/digital-books/${id}`,
    DIGITAL_BOOK_APPROVE: (id: string) => `/library/digital-books/${id}/approve`,
  },
  TIMETABLE: {
    LIST: '/timetable',
    GENERATE: '/timetable/generate',
    CONFLICTS: '/timetable/conflicts',
    SUBSTITUTE: '/timetable/substitute',
    BY_CLASS: (classId: string) => `/timetable/class/${classId}`,
    BY_TEACHER: (teacherId: string) => `/timetable/teacher/${teacherId}`,
  },
  LEAVE: {
    REQUESTS: '/leave/requests',
    MY_REQUESTS: '/leave/requests/me',
    APPROVE: (id: string) => `/leave/requests/${id}/approve`,
    REJECT: (id: string) => `/leave/requests/${id}/reject`,
  },
  SUBSTITUTE: {
    LIST: '/substitute-assignments',
    ASSIGN: (id: string) => `/substitute-assignments/${id}/assign`,
  },
  EXPENSES: {
    LIST: '/expenses',
    APPROVE: (id: string) => `/expenses/${id}/approve`,
    REJECT: (id: string) => `/expenses/${id}/reject`,
  },
  COMMUNICATION: {
    NOTICES: '/communication/notices',
    NOTICE_BY_ID: (id: string) => `/communication/notices/${id}`,
    MESSAGES: '/communication/messages',
    MESSAGE_BY_ID: (id: string) => `/communication/messages/${id}`,
    ALERTS: '/communication/alerts',
    LOGS: '/communication/logs',
  },
  PRINCIPAL: {
    KPI: '/principal/kpi',
    APPROVALS: '/principal/approvals',
    APPROVAL_BY_ID: (id: string) => `/principal/approvals/${id}`,
    STRATEGIC: '/principal/strategic',
    REPORTS: '/principal/reports',
  },
  BIOMETRIC: {
    VERIFY: '/biometric/verify',
    ENROLL: '/biometric/enroll',
    ENROLL_BY_GUARDIAN: (id: string) => `/biometric/guardian/${id}`,
    CONSENT: (id: string) => `/biometric/guardian/${id}/consent`,
    VERIFY_GUARDIAN: (id: string) => `/biometric/guardian/${id}/verify`,
    OVERRIDE_GUARDIAN: (id: string) => `/biometric/guardian/${id}/override`,
    BLACKLIST: '/biometric/blacklist',
    RELEASE_LOG: '/biometric/release-log',
    TEMP_AUTH: '/biometric/temp-auth',
  },
  SYLLABUS: {
    COVERAGE: '/syllabus/coverage',
    COVERAGE_BY_ID: (id: string) => `/syllabus/coverage/${id}`,
    DIARY: '/syllabus/diary',
    DIARY_ENTRY: (id: string) => `/syllabus/diary/${id}`,
    MONTHLY_PLAN: '/syllabus/monthly-plan',
  },
  ANALYTICS: {
    STUDENT_PATTERNS: '/analytics/student-patterns',
    ATTENDANCE_CORRELATION: '/analytics/attendance-correlation',
    TEACHER_PERFORMANCE: '/analytics/teacher-performance',
    HEATMAP: '/analytics/heatmap',
  },
  WELLBEING: {
    LOGS: '/wellbeing/logs',
    LOG_BY_ID: (id: string) => `/wellbeing/logs/${id}`,
    MOOD: '/wellbeing/mood',
    CASES: '/wellbeing/cases',
    CASE_BY_ID: (id: string) => `/wellbeing/cases/${id}`,
  },
  CAREER: {
    OCEAN: '/career/ocean',
    OCEAN_SUBMIT: '/career/ocean/submit',
    RIASEC: '/career/riasec',
    RIASEC_SUBMIT: '/career/riasec/submit',
    RESULTS: (studentId: string) => `/career/results/${studentId}`,
  },
  LMS: {
    ASSIGNMENTS: '/lms/assignments',
    ASSIGNMENT_BY_ID: (id: string) => `/lms/assignments/${id}`,
    SUBMISSIONS: (assignmentId: string) => `/lms/assignments/${assignmentId}/submissions`,
    LIVE_CLASSES: '/lms/live-classes',
    LIVE_CLASS_BY_ID: (id: string) => `/lms/live-classes/${id}`,
    LIVE_JOIN: (id: string) => `/lms/live-classes/${id}/join`,
  },
  FILES: {
    UPLOAD: '/files/upload',
    BY_ID: (id: string) => `/files/${id}`,
  },
} as const
