export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/email/login',
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
    REGISTER: '/auth/email/register',
    FORGOT_PASSWORD: '/auth/forgot/password',
    RESET_PASSWORD: '/auth/reset/password',
    MFA_VERIFY: '/auth/mfa/verify',
  },
  STUDENTS: {
    LIST: '/students',
    BY_ID: (id: string) => `/students/${id}`,
    ENROLL: '/students',
    PROMOTE: (id: string) => `/students/${id}/promote`,
    GUARDIAN_LINK: (id: string) => `/students/${id}/guardians`,
    SIBLING_LINK: (id: string) => `/students/${id}/siblings`,
    GENERATE_ID: (id: string) => `/students/${id}/id-card`,
    TIMELINE: (id: string) => `/students/${id}/timeline`,
    DOCUMENTS: (id: string) => `/students/${id}/documents`,
    SEARCH: '/students/search',
    BY_ADMISSION_NUMBER: (admissionNumber: string) => `/students/admission/${encodeURIComponent(admissionNumber)}`,
  },
  TEACHERS: {
    LIST: '/teachers',
    BY_ID: (id: string) => `/teachers/${id}`,
    ENROLL: '/teachers',
    ATTENDANCE: '/teachers/attendance',
    LEAVE: '/teachers/leave',
    LEAVE_BY_ID: (id: string) => `/teachers/leave/${id}`,
    SUBSTITUTE: '/teachers/substitute',
    PAYROLL: '/teachers/payroll',
    WORKLOAD: (id: string) => `/teachers/${id}/workload`,
    DIRECTORY: '/teachers/directory',
  },
  ATTENDANCE: {
    MARK: '/attendance',
    BULK: '/attendance/bulk',
    SUBJECT: '/attendance/subject',
    REPORTS: '/attendance/reports',
    BY_STUDENT: (id: string) => `/attendance/student/${id}`,
    BY_CLASS: '/attendance/class',
    CALENDAR: '/attendance/calendar',
  },
  GRADE_STAGES: {
    LIST: '/grade-stages',
    CREATE: '/grade-stages',
    UPDATE: (id: string) => `/grade-stages/${id}`,
    DELETE: (id: string) => `/grade-stages/${id}`,
    REORDER: '/grade-stages/reorder',
  },
  GRADES: {
    TERMS: '/grades/terms',
    ASSESSMENT_PLANS: '/grades/assessment-plans',
    MY_SUBJECT_PLANS: '/grades/assessment-plans/my-subjects',
    ASSESSMENTS: '/grades/assessments',
    ASSESSMENT_OVERRIDE: (id: string) => `/grades/assessments/${id}/override`,
    EXAMS: '/exams',
    EXAM_BY_ID: (id: string) => `/exams/${id}`,
    MARKS: '/grades/marks',
    MARKS_BULK: '/grades/marks/bulk',
    GRADING_BANDS: '/grades/grading-bands',
    RESULTS_SUBJECT: '/grades/results/subject',
    RESULTS_TERM: '/grades/results/term',
    RESULTS_CLASS: '/grades/results/class',
    PUBLISH_CLASS_RESULTS: '/grades/results/publish',
    RESULTS_PUBLISHED: '/grades/results/published',
    RESULTS_PUBLISHED_SUBJECTS: '/grades/results/published/subjects',
    RESULTS_PUBLISHED_ASSESSMENTS: '/grades/results/published/assessments',
    GRADE_TRENDS: '/grades/grade-trends',
    TOPIC_WEAKNESS: '/grades/topic-weakness',
    REPORT_CARDS: '/report-cards',
    REPORT_CARD_BY_ID: (id: string) => `/report-cards/${id}`,
    PUBLISH: (examId: string) => `/exams/${examId}/publish`,
    ANALYTICS: '/grades/analytics',
    CORRECTION: (id: string) => `/marks/${id}/correction`,
  },
  FEES: {
    STRUCTURE: '/fees/structure',
    STRUCTURE_BY_ID: (id: number) => `/fees/structure/${id}`,
    GENERATE_INVOICES: '/fees/invoices/generate',
    INVOICES: '/fees/invoices',
    INVOICE_BY_ID: (id: string) => `/fees/invoices/${id}`,
    PAYMENTS: '/fees/payments',
    DISCOUNTS: '/fees/discounts',
    SEND_DUE_REMINDERS: '/fees/reminders/due-soon',
    SEND_OVERDUE_NOTICES: '/fees/reminders/overdue',
    WAIVER_REQUESTS: '/fees/waiver-requests',
    WAIVER_REQUEST_APPROVE: (id: string) => `/fees/waiver-requests/${id}/approve`,
    WAIVER_REQUEST_REJECT: (id: string) => `/fees/waiver-requests/${id}/reject`,
    REPORTS: '/fees/reports',
    DASHBOARD: '/fees/dashboard',
  },
  LIBRARY: {
    BOOKS: '/library/books',
    BOOK_BY_ID: (id: string) => `/library/books/${id}`,
    BOOKS_BY_BARCODE: (barcode: string) => `/library/books/barcode/${barcode}`,
    ISSUANCE: '/library/issuance',
    LOANS: '/library/loans',
    LOANS_RETURN: (id: string) => `/library/loans/${id}/return`,
    FINES: '/library/fines',
    FINES_PAY: (loanId: string) => `/library/fines/${loanId}/pay`,
    DIGITAL_BOOKS: '/library/digital-books',
    DIGITAL_BOOK_BY_ID: (id: string) => `/library/digital-books/${id}`,
    DIGITAL_BOOK_APPROVE: (id: string) => `/library/digital-books/${id}/approve`,
  },
  TIMETABLE: {
    LIST: '/timetable',
    GENERATE: '/timetable/generate',
    CONFLICTS: '/timetable/conflicts',
    SUBSTITUTE: '/timetable/substitute',
    BY_CLASS: (classId: string) => `/timetable/class/${classId}`,
    BY_TEACHER: (teacherId: string) => `/timetable/teacher/${teacherId}`,
  },
  LEAVE: {
    REQUESTS: '/leave/requests',
    MY_REQUESTS: '/leave/requests/me',
    APPROVE: (id: string) => `/leave/requests/${id}/approve`,
    REJECT: (id: string) => `/leave/requests/${id}/reject`,
  },
  SUBSTITUTE: {
    LIST: '/substitute-assignments',
    ASSIGN: (id: string) => `/substitute-assignments/${id}/assign`,
  },
  EXPENSES: {
    LIST: '/expenses',
    APPROVE: (id: string) => `/expenses/${id}/approve`,
    REJECT: (id: string) => `/expenses/${id}/reject`,
  },
  COMMUNICATION: {
    NOTICES: '/communication/notices',
    NOTICE_BY_ID: (id: string) => `/communication/notices/${id}`,
    MESSAGES: '/targeted-messages',
    MESSAGE_BY_ID: (id: string) => `/targeted-messages/${id}`,
    PREVIEW_RECIPIENTS: '/targeted-messages/preview-recipients',
    ALERTS: '/communication/alerts',
    LOGS: '/communication/logs',
  },
  PRINCIPAL: {
    KPI: '/principal/kpi',
    APPROVALS: '/principal/approvals',
    APPROVAL_BY_ID: (id: string) => `/principal/approvals/${id}`,
    STRATEGIC: '/principal/strategic',
    REPORTS: '/principal/reports',
    WELLBEING_CONCERNS: '/principal/wellbeing-concerns',
  },
  BIOMETRIC: {
    VERIFY: '/biometric/verify',
    ENROLL: '/biometric/enroll',
    ENROLL_BY_GUARDIAN: (id: string) => `/biometric/guardian/${id}`,
    CONSENT: (id: string) => `/biometric/guardian/${id}/consent`,
    VERIFY_GUARDIAN: (id: string) => `/biometric/guardian/${id}/verify`,
    OVERRIDE_GUARDIAN: (id: string) => `/biometric/guardian/${id}/override`,
    BLACKLIST: '/biometric/blacklist',
    RELEASE_LOG: '/biometric/release-log',
    RELEASE_LOG_SUMMARY: '/biometric/release-log/summary',
    RELEASE_LOG_INCIDENTS: '/biometric/release-log/incidents',
    TEMP_AUTH: '/biometric/temp-auth',
  },
  SYLLABUS: {
    UNITS: '/syllabus-units',
    UNIT_BY_ID: (id: string) => `/syllabus-units/${id}`,
    UNITS_REORDER: '/syllabus-units/reorder',
    UNITS_COPY: '/syllabus-units/copy-from-year',
    COVERAGE: '/syllabus/coverage',
    COVERAGE_BY_ID: (id: string) => `/syllabus/coverage/${id}`,
    DIARY: '/syllabus/diary',
    DIARY_ENTRY: (id: string) => `/syllabus/diary/${id}`,
    MONTHLY_PLAN: '/syllabus/monthly-plan',
  },
  LESSON_PLAN: {
    ENTRIES:         '/lesson-plans',
    ENTRY:           '/lesson-plans/entry',
    COMPLETE:        '/lesson-plans/entry/complete',
    SUBMIT:          '/lesson-plans/submit',
    STATUS:          '/lesson-plans/status',
    SECTION_SUMMARY: '/lesson-plans/section-summary',
    MONTHLY:         '/lesson-plans/monthly',
    MONTH_END_SUMMARY: '/lesson-plans/month-end-summary',
  },
  CLASS_DIARY: {
    DAILY: '/class-diary/daily',
    ENTRY: '/class-diary/entry',
  },
  TEACHER_TASKS: {
    FREE_PERIOD: '/teacher-tasks/free-period',
  },
  CLASS_CHECK_IN: {
    STATUS: '/check-in/status',
    CURRENT_CLASS_ROSTER: '/check-in/current-class-roster',
    CHECK_IN: '/check-in',
    BY_ROOM: (roomId: string) => `/check-in/room/${roomId}`,
  },
  CLASS_ROOMS: {
    LIST: '/class-rooms',
    QR_PDF: '/class-rooms/qr-codes/pdf',
  },
  TEACHER_PERFORMANCE: {
    ME: '/teacher-performance/me',
    BY_STAFF: (staffId: string) => `/teacher-performance/staff/${staffId}`,
  },
  LIVE_CLASS_MONITOR: {
    STATUS: '/live-class-monitor',
  },
  LATE_ALERTS: {
    LIST: '/late-alerts',
    ACKNOWLEDGE: (id: string) => `/late-alerts/${id}/acknowledge`,
  },
  SCHOOL_SETTINGS: {
    GET: '/school-settings',
    UPDATE: '/school-settings',
  },
  SUBJECT_TOPICS: {
    LIST: '/subject-topics',
    CREATE: '/subject-topics',
    REORDER: '/subject-topics/reorder',
    RENAME: (id: string) => `/subject-topics/${id}`,
    ARCHIVE: (id: string) => `/subject-topics/${id}/archive`,
  },
  SPORT_TYPES: {
    LIST: '/sport-types',
    CREATE: '/sport-types',
    UPDATE: (id: string) => `/sport-types/${id}`,
    DELETE: (id: string) => `/sport-types/${id}`,
    METRICS: (id: string) => `/sport-types/${id}/metrics`,
    CREATE_METRIC: (id: string) => `/sport-types/${id}/metrics`,
    UPDATE_METRIC: (metricId: string) => `/sport-types/metrics/${metricId}`,
    DELETE_METRIC: (metricId: string) => `/sport-types/metrics/${metricId}`,
  },
  LAB_TYPES: {
    LIST: '/lab-types',
    CREATE: '/lab-types',
    UPDATE: (id: string) => `/lab-types/${id}`,
    DELETE: (id: string) => `/lab-types/${id}`,
  },
  LABS: {
    LIST: '/labs',
    DIRECTORY: '/labs/directory',
    CREATE: '/labs',
    UPDATE: (id: string) => `/labs/${id}`,
    DELETE: (id: string) => `/labs/${id}`,
    TOGGLE_MAINTENANCE: (id: string) => `/labs/${id}/maintenance`,
    BOOKINGS: (id: string) => `/labs/${id}/bookings`,
    CREATE_BOOKING: (id: string) => `/labs/${id}/bookings`,
    CANCEL_BOOKING: (labId: string, bookingId: string) => `/labs/${labId}/bookings/${bookingId}/cancel`,
    CREATE_RECURRING_BOOKING: (labId: string) => `/labs/${labId}/bookings/recurring`,
  },
  EQUIPMENT_CATEGORIES: {
    LIST: '/equipment-categories',
    CREATE: '/equipment-categories',
    UPDATE: (id: string) => `/equipment-categories/${id}`,
    DELETE: (id: string) => `/equipment-categories/${id}`,
  },
  EQUIPMENT: {
    LIST_FOR_LAB: (labId: string) => `/equipment/lab/${labId}`,
    CREATE_FOR_LAB: (labId: string) => `/equipment/lab/${labId}`,
    UPDATE: (id: string) => `/equipment/${id}`,
    UPDATE_CONDITION: (id: string) => `/equipment/${id}/condition`,
    CONDITION_HISTORY: (id: string) => `/equipment/${id}/condition-history`,
    WRITE_OFF: (id: string) => `/equipment/${id}/write-off`,
    REPORT: '/equipment/report',
    REPORT_EXPORT: '/equipment/report/export',
  },
  SESSION_EQUIPMENT: {
    BOOKING_REPORT: (bookingId: string) => `/session-equipment/bookings/${bookingId}/report`,
    SUBMIT_BOOKING_REPORT: (bookingId: string) => `/session-equipment/bookings/${bookingId}/report`,
    DAMAGE_REPORTS: '/session-equipment/damage-reports',
  },
  EXPERIMENT_LOGS: {
    BOOKING: (bookingId: string) => `/experiment-logs/bookings/${bookingId}`,
    UPSERT_BOOKING: (bookingId: string) => `/experiment-logs/bookings/${bookingId}`,
    HISTORY: '/experiment-logs',
  },
  LAB_REPORTS: {
    CREATE_ASSIGNMENT: (experimentLogId: string) => `/lab-reports/experiment-logs/${experimentLogId}/assignments`,
    ASSIGNMENT: (assignmentId: string) => `/lab-reports/assignments/${assignmentId}`,
    ROSTER: (assignmentId: string) => `/lab-reports/assignments/${assignmentId}/roster`,
    GRADE_SUBMISSION: (assignmentId: string, submissionId: string) =>
      `/lab-reports/assignments/${assignmentId}/submissions/${submissionId}/grade`,
    MY_CLASS: '/lab-reports/my-class',
    SUBMIT: (assignmentId: string) => `/lab-reports/assignments/${assignmentId}/submissions`,
    MY_SUBMISSION: (assignmentId: string) => `/lab-reports/assignments/${assignmentId}/submissions/me`,
    GUARDIAN_CHILD_ASSIGNMENTS: (studentId: string) => `/lab-reports/guardian/${studentId}/assignments`,
  },
  LAB_OVERVIEW: {
    DASHBOARD: '/lab-overview/dashboard',
    UTILISATION: '/lab-overview/utilisation',
    EQUIPMENT_HEALTH: '/lab-overview/equipment-health',
    EXPERIMENT_COVERAGE: '/lab-overview/experiment-coverage',
    LAB_REPORT_PERFORMANCE: '/lab-overview/lab-report-performance',
  },
  DISORDER_REGISTRY: {
    LIST: '/disorder-registry',
    DETAIL: (id: string) => `/disorder-registry/${id}`,
    CREATE: '/disorder-registry',
    UPDATE: (id: string) => `/disorder-registry/${id}`,
  },
  ACTION_RULE: {
    LIST: '/action-rules',
    CREATE: '/action-rules',
    UPDATE: (id: string) => `/action-rules/${id}`,
  },
  SAFETY_ALERTS: {
    LIST: '/safety-alerts',
  },
  ASSESSMENT_MATRIX: {
    LIST: '/assessment-matrix',
    EXPORT: '/assessment-matrix/export',
  },
  MHA_CONSENT: {
    STATUS: (studentId: string) => `/mha-consent/students/${studentId}`,
    RECORD: (studentId: string) => `/mha-consent/students/${studentId}`,
  },
  MHA_SESSION: {
    PREVIEW: '/mha-sessions/preview',
    CREATE: '/mha-sessions',
    DETAIL: (id: string) => `/mha-sessions/${id}`,
    LIST: '/mha-sessions',
    COMPLETE: (id: string) => `/mha-sessions/${id}/complete`,
    SUMMARY: (id: string) => `/mha-sessions/${id}/summary`,
    ACTION_STATUS: (sessionId: string, actionId: string) => `/mha-sessions/${sessionId}/actions/${actionId}`,
    NOTIFY_GUARDIAN: (id: string) => `/mha-sessions/${id}/notify-guardian`,
    CASELOAD: '/mha-sessions/caseload',
    HISTORY: (studentId: string) => `/mha-sessions/students/${studentId}/history`,
  },
  DOMAIN_RESULT: {
    LIST: (sessionId: string) => `/mha-sessions/${sessionId}/domain-results`,
    UPDATE: (sessionId: string, id: string) => `/mha-sessions/${sessionId}/domain-results/${id}`,
  },
  ACADEMIC_CONTEXT: {
    BY_STUDENT: (studentId: string) => `/students/${studentId}/academic-context`,
  },
  SPORTS: {
    LIST: '/sports',
    DIRECTORY: '/sports/directory',
    MY_COACHED: '/sports/my-coached',
    CREATE: '/sports',
    UPDATE: (id: string) => `/sports/${id}`,
    ROSTER: (id: string) => `/sports/${id}/roster`,
    ENROLL: (id: string) => `/sports/${id}/roster`,
    REMOVE_FROM_ROSTER: (id: string, studentId: string) => `/sports/${id}/roster/${studentId}`,
    MATCHES: (id: string) => `/sports/${id}/matches`,
    CREATE_MATCH: (id: string) => `/sports/${id}/matches`,
    UPDATE_MATCH: (id: string, matchId: string) => `/sports/${id}/matches/${matchId}`,
    PERFORMANCE: (id: string, matchId: string) => `/sports/${id}/matches/${matchId}/performance`,
    GRANT_OVERRIDE: (id: string, matchId: string, performanceId: string) =>
      `/sports/${id}/matches/${matchId}/performance/${performanceId}/override`,
    TRAINING_SESSIONS: (id: string) => `/sports/${id}/training-sessions`,
    CREATE_TRAINING_SESSION: (id: string) => `/sports/${id}/training-sessions`,
    UPDATE_TRAINING_SESSION: (id: string, sessionId: string) =>
      `/sports/${id}/training-sessions/${sessionId}`,
    PERFORMANCE_TRENDS: (id: string) => `/sports/${id}/performance-trends`,
    RECOMPUTE_SNAPSHOTS: '/sports/analysis/recompute',
    SCHOOL_DASHBOARD: '/sports/dashboard/school',
    MY_PERFORMANCE: '/sports/my-performance',
    PUBLIC_BOARD: '/sports/public-board',
    ALERTS: '/sports/alerts',
    ACKNOWLEDGE_ALERT: (id: string) => `/sports/alerts/${id}/acknowledge`,
  },
  ANALYTICS: {
    STUDENT_PATTERNS: '/analytics/student-patterns',
    ATTENDANCE_CORRELATION: '/analytics/attendance-correlation',
    TEACHER_PERFORMANCE: '/analytics/teacher-performance',
    HEATMAP: '/analytics/heatmap',
  },
  WELLBEING: {
    LOGS: '/wellbeing/logs',
    LOG_BY_ID: (id: string) => `/wellbeing/logs/${id}`,
    MOOD: '/wellbeing/mood',
    CASES: '/wellbeing/cases',
    CASE_BY_ID: (id: string) => `/wellbeing/cases/${id}`,
  },
  CAREER: {
    OCEAN: '/career/ocean',
    OCEAN_SUBMIT: '/career/ocean/submit',
    RIASEC: '/career/riasec',
    RIASEC_SUBMIT: '/career/riasec/submit',
    // Kept declared but unused: a studentId-keyed route needs a studentId<->userId bridge
    // that would require importing StudentEntity into the (deliberately isolated) career
    // module — out of scope for the student-facing self-view built so far. RESULTS_ME below
    // is what the student's own page actually calls.
    RESULTS: (studentId: string) => `/career/results/${studentId}`,
    RESULTS_ME: '/career/results/me',
  },
  LMS: {
    ASSIGNMENTS: '/lms/assignments',
    ASSIGNMENT_BY_ID: (id: string) => `/lms/assignments/${id}`,
    ASSIGNMENTS_MY_CLASS: '/lms/assignments/my-class',
    ASSIGNMENTS_MINE: '/lms/assignments/mine',
    SUBMISSIONS: (assignmentId: string) => `/lms/assignments/${assignmentId}/submissions`,
    SUBMISSION_ME: (assignmentId: string) => `/lms/assignments/${assignmentId}/submissions/me`,
    SUBMISSION_STATUSES: '/lms/assignments/submissions/statuses',
    ROSTER: (assignmentId: string) => `/lms/assignments/${assignmentId}/roster`,
    GRADE: (assignmentId: string, submissionId: string) =>
      `/lms/assignments/${assignmentId}/submissions/${submissionId}/grade`,
    FOR_CHILD: (studentId: string) => `/lms/assignments/guardian/${studentId}`,
    LIVE_CLASSES: '/lms/live-classes',
    LIVE_CLASS_BY_ID: (id: string) => `/lms/live-classes/${id}`,
    LIVE_JOIN: (id: string) => `/lms/live-classes/${id}/join`,
    LIVE_CLASSES_MY_CLASS: '/lms/live-classes/my-class',
    LIVE_CLASSES_MINE: '/lms/live-classes/mine',
    LIVE_TOKEN: (id: string) => `/lms/live-classes/${id}/token`,
    LIVE_END: (id: string) => `/lms/live-classes/${id}/end`,
    LIVE_ATTENDANCE_JOIN: (id: string) => `/lms/live-classes/${id}/attendance/join`,
    LIVE_ATTENDANCE_LEAVE: (id: string) => `/lms/live-classes/${id}/attendance/leave`,
    LIVE_ATTENDANCE_ROSTER: (id: string) => `/lms/live-classes/${id}/attendance`,
    LIVE_WHITEBOARD_SNAPSHOT: (id: string) => `/lms/live-classes/${id}/whiteboard-snapshot`,
  },
  FILES: {
    UPLOAD: '/files/upload',
    BY_ID: (id: string) => `/files/${id}`,
  },
  EVENTS: {
    LIST: '/events',
    PUBLISHED: '/events/published',
    CREATE: '/events',
    DETAIL: (id: string) => `/events/${id}`,
    PUBLISH: (id: string) => `/events/${id}/publish`,
    CANCEL: (id: string) => `/events/${id}/cancel`,
    REGISTER: (eventId: string) => `/events/${eventId}/register`,
    MY_REGISTRATIONS: '/events/registrations/me',
    CANCEL_REGISTRATION: (id: string) => `/events/registrations/${id}/cancel`,
    CHECK_IN: (eventId: string) => `/events/${eventId}/check-in`,
    ATTENDANCE_DASHBOARD: (eventId: string) => `/events/${eventId}/attendance-dashboard`,
    ATTENDANCE_REPORT_PDF: (eventId: string) => `/events/${eventId}/attendance-report/pdf`,
    PARTICIPANTS: (eventId: string) => `/events/${eventId}/participants`,
    MY_PARTICIPATION: (eventId: string) => `/events/${eventId}/participants/me`,
    BULK_CHECK_IN: (eventId: string, classSectionId: number) => `/events/${eventId}/participants/class/${classSectionId}/bulk-check-in`,
  },
} as const
