import { AppConfig } from './app-config.type';
import { AppleConfig } from '../auth-apple/config/apple-config.type';
import { AuthConfig } from '../auth/config/auth-config.type';
import { DatabaseConfig } from '../database/config/database-config.type';
import { FacebookConfig } from '../auth-facebook/config/facebook-config.type';
import { FileConfig } from '../files/config/file-config.type';
import { GoogleConfig } from '../auth-google/config/google-config.type';
import { MailConfig } from '../mail/config/mail-config.type';
import { LessonPlanConfig } from '../lesson-plan/config/lesson-plan-config.type';
import { FreePeriodConfig } from '../teacher-tasks/config/free-period-config.type';
import { GradeTrendConfig } from '../grades/config/grade-trend-config.type';
import { TopicWeaknessConfig } from '../grades/config/topic-weakness-config.type';
import { TeacherPerformanceConfig } from '../teacher-performance/config/teacher-performance-config.type';
import { WellbeingCaseConfig } from '../counselor/config/wellbeing-case-config.type';
import { CounselorNoteConfig } from '../counselor/config/counselor-note-config.type';
import { LiveSessionConfig } from '../lms/config/live-session-config.type';
import { LiveKitConfig } from '../lms/config/livekit-config.type';
import { LiveKitEgressConfig } from '../lms/config/livekit-egress-config.type';
import { SportsAnalysisConfig } from '../sports/config/sports-analysis-config.type';

export type AllConfigType = {
  app: AppConfig;
  apple: AppleConfig;
  auth: AuthConfig;
  database: DatabaseConfig;
  facebook: FacebookConfig;
  file: FileConfig;
  google: GoogleConfig;
  mail: MailConfig;
  lessonPlan: LessonPlanConfig;
  freePeriod: FreePeriodConfig;
  gradeTrend: GradeTrendConfig;
  topicWeakness: TopicWeaknessConfig;
  teacherPerformance: TeacherPerformanceConfig;
  wellbeingCase: WellbeingCaseConfig;
  counselorNote: CounselorNoteConfig;
  liveSession: LiveSessionConfig;
  livekit: LiveKitConfig;
  livekitEgress: LiveKitEgressConfig;
  sportsAnalysis: SportsAnalysisConfig;
};
